# Generated by Django 2.1.2 on 2018-12-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('addrid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('addrinfo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='orderlist',
            fields=[
                ('orderid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('ordertime', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='picture',
            fields=[
                ('picid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('picpath', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='telephone',
            fields=[
                ('teleid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('teleinfo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('ticketid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('ticketlocation', models.CharField(max_length=40)),
                ('tickettime', models.CharField(max_length=20)),
                ('ticketinfo', models.CharField(max_length=200)),
                ('ticketprice', models.IntegerField()),
                ('ticketstatus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('usersex', models.CharField(max_length=2, null=True)),
                ('userpwd', models.CharField(max_length=20)),
            ],
        ),
    ]
