# Generated by Django 2.1.2 on 2018-12-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketid', models.IntegerField()),
                ('orderid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('orderid', models.IntegerField()),
            ],
        ),
    ]
