# Generated by Django 2.1.2 on 2018-12-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_ticket_order_user_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='ordertime',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tickettime',
            field=models.CharField(max_length=40),
        ),
    ]
