# Generated by Django 2.1.2 on 2018-12-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_auto_20181213_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userimg',
            field=models.CharField(default='0.jpg', max_length=50),
        ),
    ]
