# Generated by Django 2.1.2 on 2018-12-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_user_userimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userimg',
            field=models.CharField(default='0.JPG', max_length=50),
        ),
    ]
