# Generated by Django 2.1.2 on 2018-12-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_auto_20181213_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticketimg',
            field=models.CharField(default='0.JPG', max_length=50),
        ),
    ]
